<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5895" started-at="2016-08-02T08:23:04Z" finished-at="2016-08-02T08:23:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5895" started-at="2016-08-02T08:23:04Z" finished-at="2016-08-02T08:23:10Z">
      <class name="CallReport.SaveCallReport">
        <test-method status="PASS" signature="initializeBrowser()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="initializeBrowser" is-config="true" duration-ms="8744" started-at="2016-08-02T01:22:55Z" finished-at="2016-08-02T01:23:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBrowser -->
        <test-method status="PASS" signature="InvokeUrl()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="InvokeUrl" is-config="true" duration-ms="1906" started-at="2016-08-02T01:23:04Z" finished-at="2016-08-02T01:23:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvokeUrl -->
        <test-method status="PASS" signature="login()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="login" duration-ms="3890" started-at="2016-08-02T01:23:06Z" finished-at="2016-08-02T01:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="homePage()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="homePage" duration-ms="30" started-at="2016-08-02T01:23:10Z" depends-on-methods="CallReport.SaveCallReport.login" finished-at="2016-08-02T01:23:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Possible defect - Home page title mismatch. expected [Salesforce - Enterprise Edition] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Possible defect - Home page title mismatch. expected [Salesforce - Enterprise Edition] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at CallReport.SaveCallReport.homePage(SaveCallReport.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePage -->
        <test-method status="SKIP" signature="accountHolder()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="accountHolder" duration-ms="1" started-at="2016-08-02T01:23:10Z" depends-on-methods="CallReport.SaveCallReport.homePage" finished-at="2016-08-02T01:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accountHolder -->
        <test-method status="SKIP" signature="saveCallRreport()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="saveCallRreport" duration-ms="1" started-at="2016-08-02T01:23:10Z" depends-on-methods="CallReport.SaveCallReport.accountHolder" finished-at="2016-08-02T01:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveCallRreport -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="logout" duration-ms="1" started-at="2016-08-02T01:23:10Z" description="Logging out from Veeva CRM" depends-on-methods="CallReport.SaveCallReport.saveCallRreport" finished-at="2016-08-02T01:23:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="Exit()[pri:0, instance:CallReport.SaveCallReport@2f84540b]" name="Exit" is-config="true" duration-ms="1144" started-at="2016-08-02T01:23:10Z" finished-at="2016-08-02T01:23:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Exit -->
      </class> <!-- CallReport.SaveCallReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
